[build]
  command = "gnome-terminal --tab --title='Backend' --working-directory=./backend -- npm i && npm run start ; gnome-terminal --tab --title='Frontend' --working-directory=./frontend -- npm i && npm run build"
  publish = "frontend/build"